CREATE DATABASE DB_W_URBANO;
USE DB_W_URBANO;

CREATE TABLE T_DEPARTAMENTO(
DPT_ID_DEPARTAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DPT_DEPARTAMENTO VARCHAR(30) NOT NULL,
    A_USUARIO_UPDATE VARCHAR(50) NOT NULL,
    A_USUARIO_CREATE VARCHAR(50) NOT NULL,
    A_UPDATE DATE NOT NULL,
    A_CREATE DATE NOT NULL
)ENGINE INNODB;

CREATE TABLE T_MUNICIPIO(
MNP_ID_MUNICIPIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MNP_MUNICIPIO VARCHAR(30) NOT NULL,
MNP_ID_DEPARTAMENTO INT NOT NULL,
CONSTRAINT FOREIGN KEY (MNP_ID_DEPARTAMENTO) REFERENCES T_DEPARTAMENTO(DPT_DEPARTAMENTO) ON DELETE CASCADE ON UPDATE CASCADE,
    A_USUARIO_UPDATE VARCHAR(50) NOT NULL,
    A_USUARIO_CREATE VARCHAR(50) NOT NULL,
    A_UPDATE DATE NOT NULL,
    A_CREATE DATE NOT NULL
)ENGINE INNODB;


CREATE TABLE T_ESTADO_SOLICITUD(
  STS_ID_ESTADO_SOLICITUD INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  STS_ESTADO VARCHAR(20) NOT NULL
    A_USUARIO_UPDATE VARCHAR(50) NOT NULL,
    A_USUARIO_CREATE VARCHAR(50) NOT NULL,
    A_UPDATE DATE NOT NULL,
    A_CREATE DATE NOT NULL
)ENGINE INNODB;

CREATE TABLE T_SOLICITUD(
    SLD_ID_SOLICITUD INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SLD_NOMBRE VARCHAR(50) NOT NULL,
    SLD_APELLIDO VARCHAR(50) NOT NULL,
    SLD_TELEFONO VARCHAR(15) NOT NULL,
    SLD_EMAIL VARCHAR(50) NOT NULL,
    SLD_ID_MUNICIPIO INT NOT NULL,
    SLD_DIRECCION VARCHAR (150),
    SLD_ID_ESTADO_SOLICITUD INT NOT NULL,
    SLD_INFO_ADICIONAL VARCHAR(300) NOT NULL,
    A_USUARIO_UPDATE VARCHAR(50) NOT NULL,
    A_USUARIO_CREATE VARCHAR(50) NOT NULL,
    A_UPDATE DATE NOT NULL,
    A_CREATE DATE NOT NULL,
    CONSTRAINT FOREIGN KEY (SLD_ID_MUNICIPIO) REFERENCES T_MUNICIPIO(MNP_ID_MUNICIPIO) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (SLD_ID_ESTADO_SOLICITUD) REFERENCES T_ESTADO_SOLICITUD(STS_ID_ESTADO_SOLICITUD) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE INNODB;

CREATE TABLE T_IMAGENES(
    IMG_ID_IMAGEN INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IMG_NOMBRE VARCHAR(20) NOT NULL,
    IMG_ID_SOLICITUD INT NOT NULL,
    A_USUARIO_UPDATE VARCHAR(50) NOT NULL,
    A_USUARIO_CREATE VARCHAR(50) NOT NULL,
    A_UPDATE DATE NOT NULL,
    A_CREATE DATE NOT NULL,
    CONSTRAINT FOREIGN KEY (IMG_ID_SOLICITUD) REFERENCES T_SOLICITUD(SLD_ID_SOLICITUD) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE INNODB;

CREATE TABLE T_TIPO_INMUEBLE(
  T_  
)

