CREATE DATABASE DB_W_URBANO;
USE DB_W_URBANO;

CREATE TABLE T_DEPARTAMENTO(
DPT_ID_DEPARTAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DPT_DEPARTAMENTO VARCHAR(30) NOT NULL,
A_USUARIO VARCHAR(50),
A_UPDATE DATE,
A_CREATE DATE
)ENGINE INNODB;

CREATE TABLE T_MUNICIPIO(
MNP_ID_MUNICIPIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MNP_MUNICIPIO VARCHAR(30) NOT NULL,
MNP_ID_DEPARTAMENTO INT NOT NULL,
CONSTRAINT FOREIGN KEY (MNP_ID_DEPARTAMENTO) REFERENCES T_DEPARTAMENTO(DPT_DEPARTAMENTO) ON DELETE CASCADE ON UPDATE CASCADE,
A_USUARIO VARCHAR(50),
A_UPDATE DATE,
A_CREATE DATE
)ENGINE INNODB;


